### ISSUE TITLE
Repository Initialisation 

### ISSUE THREAD

**Issue by OceanOSdev** [LTHS-Programming-Club/PE-App#2]
Can someone please initialise this thing?  It's like 1:25 and I'm just too tired to make things and stuff work now, much thanks in advance.

**Comment by OceanOSdev** [comment]
Pls

**Comment by OceanOSdev** [comment]
Pls

**Comment by ordelore** [comment]
Whomever created the repository needs to be the one who adds at least a README

**Comment by OceanOSdev** [comment]
killian gave me a good reason, so yeah
